AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  most-wanted-labels-api

  Sample SAM Template for most-wanted-labels-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  MostWantedLabelsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: AWSLambdaDynamoDBExecutionRole
      Events:
        GetRecordLabels:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/record-labels
            Method: get
        PostRecordLabel:
          Type: Api
          Properties:
            Path: /api/record-labels/add-new
            Method: post
        GetRecordLabel:
          Type: Api
          Properties:
            Path: /api/record-labels/{record_label_id}
            Method: get
  MostWantedLabelsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: record_label_id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: overall_label_score
          AttributeType: N
        - AttributeName: average_want
          AttributeType: N
        - AttributeName: average_have
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: record_label_id
          KeyType: RANGE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MostWantedLabelsApi:
    Description: "API Gateway endpoint URL for Prod stage for Most Wanted Labels function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/most-wanted-labels/"
  MostWantedLabelsFunction:
    Description: "Most Wanted Labels Lambda Function ARN"
    Value: !GetAtt MostWantedLabelsFunction.Arn
  MostWantedLabelsFunctionIamRole:
    Description: "Implicit IAM Role created for Most Wanted Labels function"
    Value: !GetAtt MostWantedLabelsFunctionRole.Arn
  MostWantedLabelsTable:
    Description: "Most Wanted Labels DynamoDB Table ARN"
    Value: !GetAtt MostWantedLabelsTable.Arn
