AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  most-wanted-labels-api

  Sample SAM Template for most-wanted-labels-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MostWantedLabelsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        RecordLabels:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/record-labels
            Method: get
        RecordLabel:
          Type: Api
          Properties:
            Path: /api/record-labels/{id}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MostWantedLabelsApi:
    Description: "API Gateway endpoint URL for Prod stage for Most Wanted Labels function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/most-wanted-labels/"
  MostWantedLabelsFunction:
    Description: "Most Wanted Labels Lambda Function ARN"
    Value: !GetAtt MostWantedLabelsFunction.Arn
  MostWantedLabelsFunctionIamRole:
    Description: "Implicit IAM Role created for Most Wanted Labels function"
    Value: !GetAtt MostWantedLabelsFunctionRole.Arn
